# Generated by Django 3.2.13 on 2022-07-27 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("collector", "0001_initial"),
        ("collector", "0002_auto_20220524_0436"),
        ("collector", "0003_place_user"),
        ("collector", "0004_auto_20220525_0301"),
        ("collector", "0005_auto_20220525_0307"),
        ("collector", "0006_auto_20220525_0318"),
        ("collector", "0007_alter_place_user"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("name", models.CharField(max_length=128, verbose_name="Name place")),
                ("description", models.TextField(verbose_name="Description of place")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner of post about place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Place",
                "verbose_name_plural": "Places",
            },
        ),
    ]
