# Generated by Django 3.2.13 on 2022-05-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(verbose_name="Description of place"),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Latitude place"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Longitude place"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name place"),
        ),
    ]
