# Generated by Django 3.2.13 on 2022-05-24 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("collector", "0002_auto_20220524_0436"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="Owner of post about place",
            ),
            preserve_default=False,
        ),
    ]
