# Generated by Django 3.2.13 on 2022-05-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collector", "0004_auto_20220525_0301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                decimal_places=5, max_digits=10, verbose_name="Latitude place"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                decimal_places=5, max_digits=10, verbose_name="Longitude place"
            ),
        ),
    ]
