# Generated by Django 3.2.13 on 2022-05-29 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("collector", "0006_auto_20220525_0318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner of post about place",
            ),
        ),
    ]
